[package]
name = "data-structures-and-algorithms"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["cargo"] }

[dev-dependencies]
anyhow = "1"
